%YAML:1.0

Regulariser:
  TV:
    0
  TGV:
    1
  LOG_TV:
    0
  LOG_TGV:
    0
  sigma:
    125.0
  tau:
    0.001
  lambda:
    0.5
  theta:
    0.5
  alpha_1:
    1
  alpha_2:
    1
  beta:
    1
  iterations:
    4000
  outer_iterations:
    20

Viewer:
  max_depth:
    50
  colour_scale:
    1

Camera:
  baseline:
    0.5376
  CameraMatrix: !!opencv-matrix
    rows: 3
    cols: 3
    dt: f
    data: [ 718 ,    0.     ,  607,
              0.     ,  718,  185,
              0.     ,    0.     ,    1. ]
FeatureExtractor:
  num_features:
      4000
  num_levels:
      1
  scale_factor:
      1.2
  initial_fast_threshold:
      10
  minimum_fast_threshold:
      7
  patch_size:
      31
  half_patch_size:
    31
  edge_threshold:
      19
FeatureMatcher:
  match_threshold_high:
      100
  match_threshold_low:
      50
  stereo_baseline:
      0.5376
  focal_length:
      718


