%YAML:1.0

Viewer:
  max_depth:
    40
  colour_scale:
    1.5

Camera:
  height:
    720
  width:
    1280
  baseline:
    0.12
  CameraMatrix: !!opencv-matrix
    rows: 3
    cols: 3
    dt: f
    data: [531.14774, 0., 637.87114, 
           0., 531.26312, 331.27469,
           0., 0., 1. ]

FeatureExtractor:
  num_features:
    6000
  num_levels:
    8
  scale_factor:
    0.5
  initial_fast_threshold:
    20
  minimum_fast_threshold:
    7
  patch_size:
    31
  half_patch_size:
    15
  edge_threshold:
    19
FeatureMatcher:
  match_threshold_high:
    100
  match_threshold_low:
    50
  stereo_baseline:
    0.12
  focal_length:
    531.14774

FeatureSolver:
  ransac_prob:
    0.95
  ransac_max_iterations:
    1000
  inlier_threshold:
    3.0
  CameraMatrix: !!opencv-matrix
    rows: 3
    cols: 3
    dt: f
    data: [ 531.14774, 0., 637.87114, 
           0., 531.26312, 331.27469,
           0., 0., 1. ]
